// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.21.1
// source: move.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//package chess;
type MsgType int32

const (
	MsgType_BaseMsgType      MsgType = 0
	MsgType_JoinRoomMsgType  MsgType = 1
	MsgType_LeaveRoomMsgType MsgType = 2
	MsgType_RoomsMsgType     MsgType = 3
	MsgType_MoveMsgType      MsgType = 4
	MsgType_MessageMsgType   MsgType = 5
	MsgType_OrderMsgType     MsgType = 6
	MsgType_ChessMapMsgType  MsgType = 7
	MsgType_ResultMsgType    MsgType = 8
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "BaseMsgType",
		1: "JoinRoomMsgType",
		2: "LeaveRoomMsgType",
		3: "RoomsMsgType",
		4: "MoveMsgType",
		5: "MessageMsgType",
		6: "OrderMsgType",
		7: "ChessMapMsgType",
		8: "ResultMsgType",
	}
	MsgType_value = map[string]int32{
		"BaseMsgType":      0,
		"JoinRoomMsgType":  1,
		"LeaveRoomMsgType": 2,
		"RoomsMsgType":     3,
		"MoveMsgType":      4,
		"MessageMsgType":   5,
		"OrderMsgType":     6,
		"ChessMapMsgType":  7,
		"ResultMsgType":    8,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_move_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_move_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{0}
}

type BaseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
}

func (x *BaseMsg) Reset() {
	*x = BaseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMsg) ProtoMessage() {}

func (x *BaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMsg.ProtoReflect.Descriptor instead.
func (*BaseMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

type JoinRoomMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	RoomId  int32   `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Join    bool    `protobuf:"varint,3,opt,name=join,proto3" json:"join,omitempty"`     //join success?
	Player  bool    `protobuf:"varint,4,opt,name=player,proto3" json:"player,omitempty"` //is player or viewer?
}

func (x *JoinRoomMsg) Reset() {
	*x = JoinRoomMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomMsg) ProtoMessage() {}

func (x *JoinRoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomMsg.ProtoReflect.Descriptor instead.
func (*JoinRoomMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoomMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *JoinRoomMsg) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRoomMsg) GetJoin() bool {
	if x != nil {
		return x.Join
	}
	return false
}

func (x *JoinRoomMsg) GetPlayer() bool {
	if x != nil {
		return x.Player
	}
	return false
}

type LeaveRoomMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType  MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	ClientId string  `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"` //who leave?
	Leave    bool    `protobuf:"varint,3,opt,name=leave,proto3" json:"leave,omitempty"`      //leave success?
}

func (x *LeaveRoomMsg) Reset() {
	*x = LeaveRoomMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomMsg) ProtoMessage() {}

func (x *LeaveRoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomMsg.ProtoReflect.Descriptor instead.
func (*LeaveRoomMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRoomMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *LeaveRoomMsg) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LeaveRoomMsg) GetLeave() bool {
	if x != nil {
		return x.Leave
	}
	return false
}

type RoomMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    int32 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	NumPeople int32 `protobuf:"varint,2,opt,name=num_people,json=numPeople,proto3" json:"num_people,omitempty"`
}

func (x *RoomMsg) Reset() {
	*x = RoomMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMsg) ProtoMessage() {}

func (x *RoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMsg.ProtoReflect.Descriptor instead.
func (*RoomMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{3}
}

func (x *RoomMsg) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomMsg) GetNumPeople() int32 {
	if x != nil {
		return x.NumPeople
	}
	return 0
}

type RoomsMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType  MsgType    `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	ClientId string     `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"` //who wants clientId
	Rooms    []*RoomMsg `protobuf:"bytes,10,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *RoomsMsg) Reset() {
	*x = RoomsMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomsMsg) ProtoMessage() {}

func (x *RoomsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomsMsg.ProtoReflect.Descriptor instead.
func (*RoomsMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{4}
}

func (x *RoomsMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *RoomsMsg) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RoomsMsg) GetRooms() []*RoomMsg {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type MoveMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType    MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	MoveX      int32   `protobuf:"varint,2,opt,name=move_x,json=moveX,proto3" json:"move_x,omitempty"`
	MoveY      int32   `protobuf:"varint,3,opt,name=move_y,json=moveY,proto3" json:"move_y,omitempty"`
	Validation bool    `protobuf:"varint,4,opt,name=validation,proto3" json:"validation,omitempty"`
}

func (x *MoveMsg) Reset() {
	*x = MoveMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMsg) ProtoMessage() {}

func (x *MoveMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMsg.ProtoReflect.Descriptor instead.
func (*MoveMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{5}
}

func (x *MoveMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *MoveMsg) GetMoveX() int32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *MoveMsg) GetMoveY() int32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

func (x *MoveMsg) GetValidation() bool {
	if x != nil {
		return x.Validation
	}
	return false
}

type MessageMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType  MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	Message  string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClientId string  `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"` //client who send this message
}

func (x *MessageMsg) Reset() {
	*x = MessageMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMsg) ProtoMessage() {}

func (x *MessageMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMsg.ProtoReflect.Descriptor instead.
func (*MessageMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{6}
}

func (x *MessageMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *MessageMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageMsg) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type OrderMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType   MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	White     string  `protobuf:"bytes,2,opt,name=white,proto3" json:"white,omitempty"`          //clientId: first
	Black     string  `protobuf:"bytes,3,opt,name=black,proto3" json:"black,omitempty"`          //clientId:second
	Gamestart bool    `protobuf:"varint,4,opt,name=gamestart,proto3" json:"gamestart,omitempty"` //true for start and false for gameover
}

func (x *OrderMsg) Reset() {
	*x = OrderMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMsg) ProtoMessage() {}

func (x *OrderMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMsg.ProtoReflect.Descriptor instead.
func (*OrderMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{7}
}

func (x *OrderMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *OrderMsg) GetWhite() string {
	if x != nil {
		return x.White
	}
	return ""
}

func (x *OrderMsg) GetBlack() string {
	if x != nil {
		return x.Black
	}
	return ""
}

func (x *OrderMsg) GetGamestart() bool {
	if x != nil {
		return x.Gamestart
	}
	return false
}

type ChessMapMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	Map     []int32 `protobuf:"varint,2,rep,packed,name=map,proto3" json:"map,omitempty"`
	Step    int32   `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *ChessMapMsg) Reset() {
	*x = ChessMapMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChessMapMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessMapMsg) ProtoMessage() {}

func (x *ChessMapMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessMapMsg.ProtoReflect.Descriptor instead.
func (*ChessMapMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{8}
}

func (x *ChessMapMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *ChessMapMsg) GetMap() []int32 {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *ChessMapMsg) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type ResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType MsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=move.MsgType" json:"msg_type,omitempty"`
	Color   int32   `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *ResultMsg) Reset() {
	*x = ResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_move_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMsg) ProtoMessage() {}

func (x *ResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMsg.ProtoReflect.Descriptor instead.
func (*ResultMsg) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{9}
}

func (x *ResultMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_BaseMsgType
}

func (x *ResultMsg) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

var File_move_proto protoreflect.FileDescriptor

var file_move_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x6f,
	0x76, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a,
	0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07,
	0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7b, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x6a, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x61, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x22, 0x40, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x5f, 0x70, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x22, 0x75, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x28,
	0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d,
	0x73, 0x67, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x81, 0x01, 0x0a, 0x07, 0x4d, 0x6f,
	0x76, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6d, 0x6f, 0x76, 0x65, 0x58, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x59, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6c, 0x0a,
	0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d,
	0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x08, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65,
	0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x61, 0x63, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x12, 0x1c, 0x0a,
	0x09, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x5d, 0x0a, 0x0b, 0x43,
	0x68, 0x65, 0x73, 0x73, 0x4d, 0x61, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x73,
	0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d,
	0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x22, 0x4b, 0x0a, 0x09, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x65,
	0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2a, 0xb6, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x10,
	0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x73,
	0x73, 0x4d, 0x61, 0x70, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x10, 0x07, 0x12, 0x11, 0x0a,
	0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x10, 0x08,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_move_proto_rawDescOnce sync.Once
	file_move_proto_rawDescData = file_move_proto_rawDesc
)

func file_move_proto_rawDescGZIP() []byte {
	file_move_proto_rawDescOnce.Do(func() {
		file_move_proto_rawDescData = protoimpl.X.CompressGZIP(file_move_proto_rawDescData)
	})
	return file_move_proto_rawDescData
}

var file_move_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_move_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_move_proto_goTypes = []interface{}{
	(MsgType)(0),         // 0: move.MsgType
	(*BaseMsg)(nil),      // 1: move.BaseMsg
	(*JoinRoomMsg)(nil),  // 2: move.JoinRoomMsg
	(*LeaveRoomMsg)(nil), // 3: move.LeaveRoomMsg
	(*RoomMsg)(nil),      // 4: move.RoomMsg
	(*RoomsMsg)(nil),     // 5: move.RoomsMsg
	(*MoveMsg)(nil),      // 6: move.MoveMsg
	(*MessageMsg)(nil),   // 7: move.MessageMsg
	(*OrderMsg)(nil),     // 8: move.OrderMsg
	(*ChessMapMsg)(nil),  // 9: move.ChessMapMsg
	(*ResultMsg)(nil),    // 10: move.ResultMsg
}
var file_move_proto_depIdxs = []int32{
	0,  // 0: move.BaseMsg.msg_type:type_name -> move.MsgType
	0,  // 1: move.JoinRoomMsg.msg_type:type_name -> move.MsgType
	0,  // 2: move.LeaveRoomMsg.msg_type:type_name -> move.MsgType
	0,  // 3: move.RoomsMsg.msg_type:type_name -> move.MsgType
	4,  // 4: move.RoomsMsg.rooms:type_name -> move.RoomMsg
	0,  // 5: move.MoveMsg.msg_type:type_name -> move.MsgType
	0,  // 6: move.MessageMsg.msg_type:type_name -> move.MsgType
	0,  // 7: move.OrderMsg.msg_type:type_name -> move.MsgType
	0,  // 8: move.ChessMapMsg.msg_type:type_name -> move.MsgType
	0,  // 9: move.ResultMsg.msg_type:type_name -> move.MsgType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_move_proto_init() }
func file_move_proto_init() {
	if File_move_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_move_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoomMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomsMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChessMapMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_move_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_move_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_move_proto_goTypes,
		DependencyIndexes: file_move_proto_depIdxs,
		EnumInfos:         file_move_proto_enumTypes,
		MessageInfos:      file_move_proto_msgTypes,
	}.Build()
	File_move_proto = out.File
	file_move_proto_rawDesc = nil
	file_move_proto_goTypes = nil
	file_move_proto_depIdxs = nil
}
